Vagrant.configure("2") do |config|
    config.vm.box = "hsmnn/proxmox-ve"

    (1..3).each do |i|
        config.vm.define "proxmox-node-#{i}" do |node|
            node.vm.network "private_network", ip: "192.168.1.#{i}"
            node.vm.network "forwarded_port", guest: 8006, host: "800#{i}", auto_correct: true
            node.vm.provider :virtualbox do |vb|
                vb.name = "proxmox-node-#{i}"
            end
        end
    end
end

